language: go
go:
    - 1.12.5
    - tip
matrix:
  allow_failures:
    - go: tip

notifications:
    email:
        recipients: dean.karn@gmail.com
        on_success: change
        on_failure: always

before_install:
  - go get -u github.com/go-playground/overalls
  - go get -u github.com/mattn/goveralls
  - go get -u github.com/client9/misspell/cmd/misspell

script:
 - find . -type f | xargs misspell -source=text
 - gofmt -d -s .
 - make lint
 - make test

after_success: |
  [ $TRAVIS_GO_VERSION = 1.12.5 ] &&
  overalls -project="github.com/go-playground/pure" -covermode=count -ignore=.git,examples -debug &&
  goveralls -coverprofile=overalls.coverprofile -service travis-ci -repotoken $COVERALLS_TOKEN