language: go
go:
    - 1.12.5
    - tip
matrix:
  allow_failures:
    - go: tip

notifications:
    email:
        recipients: dean.karn@gmail.com
        on_success: change
        on_failure: always

before_install:
  - GO111MODULE=on go get -u github.com/go-playground/overalls
  - GO111MODULE=on go get -u github.com/mattn/goveralls

script:
 - GO111MODULE=on go mod download
 - make lint
 - make test

after_success: |
  [ $TRAVIS_GO_VERSION = 1.12.5 ] &&
  overalls -project="github.com/go-playground/pure" -covermode=count -ignore=.git,examples -debug &&
  goveralls -coverprofile=overalls.coverprofile -service travis-ci -repotoken $COVERALLS_TOKEN